# Generated by Django 2.1.7 on 2019-04-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
